### ISSUE TITLE
Tear down instruction in README.md omits serviceaccounts

### ISSUE THREAD

**Issue by toreanderson** [leoluk/openshift-netbox#9]
README.md says that to tear down, you need to issue `oc delete all,secret,pvc,configmap -l app=netbox`.

This leaves behind a `netbox` service account, however, so trying to rebuild the app from scratch again afterwards ends up failing with `Error from server (AlreadyExists): serviceaccounts "netbox" already exists`.

This seems to work: `oc delete all,secret,pvc,configmap,serviceaccount -l app=netbox`

Let me know if you want me to prep a pull request!

**Comment by leoluk** [comment]
Good catch, thanks!
